name: Validate JSON Submissions
on:
  pull_request:
    paths:
      - '**/*.json'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install AJV CLI
        run: npm install -g ajv-cli
      - name: Validate changed JSON files
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.json$' || true)
          for file in $files; do
            echo "Validating $file against schema.json"
            ajv validate -s schema.json -d "$file"
          done